apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms-backend
  labels:
    app: cms-backend

spec:
  replicas: 1
  selector:
    matchLabels:
      app: cms-backend
  template:
    metadata:
      labels:
        app: cms-backend
    spec:
      containers:
      - name: cms-backend
        image: euclidee/cms-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
        env:
        - name: DATABASE_URL
          value: postgresql://cms:cms@cms-database:5432/cmsdb
        - name: PORT
          value: "3001"
---
apiVersion: v1
kind: Service
metadata:
  name: cms-backend
  labels:
    app: cms-backend
spec:
  type: ClusterIP
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app: cms-backend
